// Buffer copy kernel
#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
layout(push_constant) uniform Parameters { uint count; };
layout(binding = 0) readonly buffer SrcBuf { float data_src[]; };
layout(binding = 1) writeonly buffer DstBuf { float data_dst[]; };
void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= count) return;
    data_dst[idx] = data_src[idx];
}
