//! Build script for kiln-vulkan-kernel.
//!
//! Compiles GLSL compute shaders to SPIR-V at build time using `glslc`,
//! then embeds them into the binary via `include_bytes!` macros.
//!
//! This avoids the runtime `glslc` shellout, which is unsuitable for
//! production (source tree is read-only, glslc may not be on PATH, etc.)

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

/// Shader files to compile. Format: (base_name, output_module_name).
const SHADERS: &[(&str, &str)] = &[
    ("full_attn_qkv_decode", "SPIR_V_FULL_ATTN_QKV_DECODE"),
    ("gdn_gates", "SPIR_V_GDN_GATES"),
    (
        "gdn_decode_gates_recurrent_rmsnorm",
        "SPIR_V_GDN_DECODE_GATES_RECURRENT_RMSNORM",
    ),
    ("gdn_in_proj_decode", "SPIR_V_GDN_IN_PROJ_DECODE"),
    (
        "gdn_in_proj_decode_batched",
        "SPIR_V_GDN_IN_PROJ_DECODE_BATCHED",
    ),
    ("gdn_gated_rms_norm", "SPIR_V_GDN_GATED_RMS_NORM"),
    ("causal_conv1d", "SPIR_V_CAUSAL_CONV1D"),
    (
        "causal_conv1d_state_advance",
        "SPIR_V_CAUSAL_CONV1D_STATE_ADVANCE",
    ),
    ("solve_tri", "SPIR_V_SOLVE_TRI"),
    ("gdn_recurrent_prefill", "SPIR_V_GDN_RECURRENT_PREFILL"),
    ("gdn_chunk_prep", "SPIR_V_GDN_CHUNK_PREP"),
    ("gdn_full_chunk_forward", "SPIR_V_GDN_FULL_CHUNK_FORWARD"),
    ("gdn_chunk_scan", "SPIR_V_GDN_CHUNK_SCAN"),
    ("linear_decode", "SPIR_V_LINEAR_DECODE"),
    ("linear_decode_batched", "SPIR_V_LINEAR_DECODE_BATCHED"),
    (
        "linear_decode_argmax_blocks",
        "SPIR_V_LINEAR_DECODE_ARGMAX_BLOCKS",
    ),
    (
        "linear_decode_argmax_reduce",
        "SPIR_V_LINEAR_DECODE_ARGMAX_REDUCE",
    ),
    ("mlp_gate_up_decode", "SPIR_V_MLP_GATE_UP_DECODE"),
    (
        "mlp_gate_up_decode_batched",
        "SPIR_V_MLP_GATE_UP_DECODE_BATCHED",
    ),
    ("flash_attn", "SPIR_V_FLASH_ATTN"),
];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let csrc_dir = manifest_dir.join("csrc/shaders");

    // Ensure the output directory exists
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::create_dir_all(&out_dir).unwrap();

    // Compile each shader
    for (name, _var_name) in SHADERS {
        let glsl_path = csrc_dir.join(format!("{}.comp", name));
        let spv_path = out_dir.join(format!("{}.spv", name));

        if !glsl_path.exists() {
            eprintln!(
                "cargo:warning=GLSL shader not found: {}",
                glsl_path.display()
            );
            continue;
        }

        let output = std::process::Command::new("glslc")
            .arg(&glsl_path)
            .arg("-o")
            .arg(&spv_path)
            .arg("-DFLOAT_TYPE=float")
            .arg("-DUSE_BFLOAT16=1")
            .arg("-DUSE_SUBGROUP_ADD=1")
            .arg("-DUSE_SUBGROUP_CLUSTERED=1")
            .output();

        match &output {
            Ok(output) if output.status.success() => {
                // silent on success — println! from build.rs is invisible to cargo
            }
            Ok(output) => {
                eprintln!(
                    "cargo:warning=glslc failed for {}: {} — shaders will compile at runtime",
                    name,
                    String::from_utf8_lossy(&output.stderr)
                );
            }
            Err(e) => {
                eprintln!(
                    "cargo:warning=glslc not found ({}) — Vulkan shaders will compile at runtime (or fail with a clear error)",
                    e
                );
            }
        }
    }

    // Generate the Rust code with include_bytes! macros
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit\n");
    out.push_str("// Vulkan SPIR-V shader modules embedded at build time\n\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub mod spirv_modules {\n");
    for (name, var_name) in SHADERS {
        let spv_path = out_dir.join(format!("{}.spv", name));
        if spv_path.exists() {
            let spv_bytes = fs::read(&spv_path).unwrap_or_default();
            let len = spv_bytes.len();
            out.push_str(&format!(
                "    /// Embedded SPIR-V for {}.comp ({len} bytes)\n",
                name
            ));
            out.push_str(&format!(
                "    pub const {}: &[u8] = include_bytes!(\"{}\");\n\n",
                var_name,
                spv_path.display()
            ));
        } else {
            // Fallback: empty bytes (will trigger runtime compilation if needed)
            out.push_str(&format!(
                "    /// Shader {} not compiled at build time\n",
                name
            ));
            out.push_str(&format!("    pub const {}: &[u8] = &[];\n\n", var_name));
        }
    }
    out.push_str("}\n");

    // Write the generated file
    let generated_path = out_dir.join("vulkan_spirv.rs");
    let mut file = fs::File::create(&generated_path).unwrap();
    file.write_all(out.as_bytes()).unwrap();

    println!("cargo:rerun-if-changed=csrc/shaders/");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=PATH");
}
