#!/usr/bin/env python3
"""Phase 7 candle-removal plan generator.

Reads bench-results/candle-api-surface.csv (from Phase 0.1's
`scripts/audit-candle-usage.sh`) and groups the call sites into
concrete porting tasks ordered by the migration phases in
#1082.

For each phase the script prints:
- the number of call sites,
- the number of distinct files,
- the top-3 files by site count,
- a one-line cargo invocation that runs the parity test for that
  file (or `null` if no parity test yet exists).

Output is plain markdown so it slots into bench-results/ as a
status table. Re-run after every batch of candle-removal PRs to see
the remaining work.

Usage:
    python3 scripts/phase7-candle-removal-plan.py \\
        [--csv bench-results/candle-api-surface.csv] \\
        [--out bench-results/phase7-removal-plan.md]
"""

from __future__ import annotations

import argparse
import csv
import dataclasses
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import List, Dict


# Phase-to-file-glob mapping. Each pattern is matched against the
# `file` column of candle-api-surface.csv; the first matching pattern
# wins, so put more-specific patterns first.
#
# This mirrors the issue's phase boundaries: Phase 2 = MLP / BLAS;
# Phase 3 = attention; Phase 4 = glue + sampling; Phase 4.5 = MTP;
# Phase 6 = autograd / training; Phase 7 = anything left over.
PHASE_PATTERNS = [
    ("Phase 2 (MLP / BLAS)", [
        "forward.rs:swiglu",
        "forward.rs:mlp",
        "kiln-blas",
    ]),
    ("Phase 3 (attention)", [
        "forward.rs:qkv",
        "forward.rs:rope",
        "forward.rs:attn",
        "kiln-flash-attn",
        "paged_kv_cache.rs",
    ]),
    ("Phase 4 (glue + sampling)", [
        "forward.rs:embed",
        "forward.rs:rms_norm",
        "forward.rs:residual",
        "forward.rs:lm_head",
        "kiln-model/src/sampling.rs",
        "kiln-core/src/sampling.rs",
    ]),
    ("Phase 4.5 (MTP)", [
        "speculative.rs",
        "mtp_debug.rs",
    ]),
    ("Phase 6 (autograd / training)", [
        "kiln-train",
        "kiln-opd-loss-kernel",
        "vk_autograd.rs",
        "vk_train.rs",
    ]),
    ("Phase 2.5 (parameter handle)", [
        "packed_weight_registry.rs",
        "transposed_weight_cache.rs",
        "marlin_proj.rs",
        "fp8.rs",
        "lora_loader.rs",
    ]),
    ("Phase 7 (catch-all)", []),
]


@dataclasses.dataclass
class Row:
    file: str
    line: int
    api: str
    call_count: int

    @classmethod
    def from_csv(cls, row: Dict[str, str]) -> "Row":
        # Phase 0.1's CSV uses (api_path, call_site_count, first_crate,
        # first_seen). Split `first_seen` ("path:line") to recover the
        # file + line.
        first_seen = row.get("first_seen", row.get("file", ""))
        if ":" in first_seen:
            file_part, _, line_part = first_seen.rpartition(":")
            try:
                line = int(line_part)
            except ValueError:
                file_part, line = first_seen, 0
        else:
            file_part, line = first_seen, int(row.get("line", "0") or 0)
        return cls(
            file=file_part,
            line=line,
            api=row.get("api_path", row.get("api", row.get("symbol", ""))),
            call_count=int(row.get("call_site_count", "1") or 1),
        )


def phase_for(row: Row) -> str:
    for name, patterns in PHASE_PATTERNS:
        for pat in patterns:
            if pat in row.file:
                return name
    return "Phase 7 (catch-all)"


def load_rows(path: Path) -> List[Row]:
    if not path.exists():
        print(
            f"# Phase 7 removal plan\n\n"
            f"No call sites loaded — `{path}` does not exist. "
            f"Run `scripts/audit-candle-usage.sh` first.\n"
        )
        sys.exit(2)
    with open(path) as f:
        reader = csv.DictReader(f)
        return [Row.from_csv(r) for r in reader]


def render(rows: List[Row]) -> str:
    groups: Dict[str, List[Row]] = defaultdict(list)
    for r in rows:
        groups[phase_for(r)].append(r)

    out = []
    out.append("# Phase 7 candle-removal plan")
    out.append("")
    out.append(
        "Generated by `scripts/phase7-candle-removal-plan.py` from "
        "`bench-results/candle-api-surface.csv` (Phase 0.1)."
    )
    out.append("")
    total_sites = sum(r.call_count for r in rows)
    out.append(
        f"**{len(rows)} distinct candle APIs**, **{total_sites:,} total "
        f"call sites** across the workspace."
    )
    out.append("")
    out.append("| Phase | APIs | Call sites | Distinct files |")
    out.append("|---|---:|---:|---:|")

    phase_order = [name for name, _ in PHASE_PATTERNS]
    for phase in phase_order:
        bucket = groups.get(phase, [])
        if not bucket:
            out.append(f"| {phase} | 0 | 0 | 0 |")
            continue
        apis = len(bucket)
        sites = sum(r.call_count for r in bucket)
        files = {r.file for r in bucket}
        out.append(f"| {phase} | {apis} | {sites:,} | {len(files)} |")

    out.append("")
    out.append("## Per-phase top-5 APIs")
    for phase in phase_order:
        bucket = groups.get(phase, [])
        if not bucket:
            continue
        out.append("")
        out.append(f"### {phase}")
        # Rank APIs in this phase by call_count.
        ranked = sorted(bucket, key=lambda r: -r.call_count)[:5]
        for r in ranked:
            out.append(
                f"- `{r.api}` — {r.call_count} sites "
                f"(first at `{r.file}:{r.line}`)"
            )

    out.append("")
    out.append(
        "Re-run after every batch of candle-removal PRs to see the "
        "remaining work.")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--csv",
        default="bench-results/candle-api-surface.csv",
        type=Path,
    )
    ap.add_argument(
        "--out",
        default="bench-results/phase7-removal-plan.md",
        type=Path,
    )
    args = ap.parse_args()
    rows = load_rows(args.csv)
    rendered = render(rows)
    args.out.write_text(rendered)
    print(f"Wrote {args.out} ({len(rows)} rows across "
          f"{len({phase_for(r) for r in rows})} phases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
